CREATE TABLE survey_responses (
    survey_year INT,
    response_id VARCHAR(50),
    country VARCHAR(100),
    job_role VARCHAR(100),
    experience_years NUMERIC,
    education VARCHAR(200),
    industry VARCHAR(200),
    company_size VARCHAR(200),
    org_size VARCHAR(200),
    remote_mode VARCHAR(50),
    ai_usage VARCHAR(50),
    ai_is_threat VARCHAR(50),
    ai_concerns TEXT,
    ai_sentiment VARCHAR(50),
    salary NUMERIC,
    currency VARCHAR(20),
    job_satisfaction VARCHAR(50),
    age VARCHAR(50),
    language_have_worked_with TEXT,
    platform_have_worked_with TEXT
);


CREATE TABLE linkedin_jobs (
    job_id VARCHAR(50),
    company_name VARCHAR(200),
    title VARCHAR(200),
    max_salary NUMERIC,
    pay_period VARCHAR(50),
    location VARCHAR(100),
    company_id VARCHAR(50),
    med_salary NUMERIC,
    min_salary NUMERIC,
    formatted_work_type VARCHAR(100),
    original_listed_time BIGINT,
    remote_allowed VARCHAR(50),
    application_type VARCHAR(100),
    formatted_experience_level VARCHAR(100),
    skills_desc TEXT,
    listed_time BIGINT,
    sponsored BOOLEAN,
    work_type VARCHAR(50),
    currency VARCHAR(50),
    compensation_type VARCHAR(50),
    normalized_salary NUMERIC,
    job_year INT,
    job_country VARCHAR(100),
    salary NUMERIC,
    job_family VARCHAR(50),
    exp_bucket VARCHAR(50),
    requires_ai_skill BOOLEAN
);
